"""empty message

Revision ID: 0bd1404fd9db
Revises: 8754f31b6738
Create Date: 2021-10-19 17:05:03.189259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bd1404fd9db'
down_revision = '8754f31b6738'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('title', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'title')
    # ### end Alembic commands ###
