"""empty message

Revision ID: 0794ed5d68e5
Revises: d30c97c10d92
Create Date: 2021-12-02 14:37:16.713683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0794ed5d68e5'
down_revision = 'd30c97c10d92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('video_likes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_likes',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('video_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='video_likes_user_id_fkey'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], name='video_likes_video_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'video_id', name='video_likes_pkey')
    )
    op.drop_table('likes')
    # ### end Alembic commands ###
